name: CI/CD Web-Porto (Laravel)

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Deploy Directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p /root/workspace/web-porto

      - name: Copy Config and .env to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.yml,.env,nginx"
          target: "/root/workspace/web-porto"
          rm: false
          strip_components: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            export $(cat /root/.env | xargs)

            cd /root/workspace/web-porto

            docker-compose down -v

            docker-compose pull
            docker-compose up -d --force-recreate

            sudo mkdir -p storage/framework/sessions storage/framework/views storage/logs bootstrap/cache
            sudo chown -R www-data:www-data storage bootstrap
            sudo chmod -R 775 storage bootstrap

            sleep 5

            if docker ps --format '{{.Names}}' | grep -q "${{ secrets.IMAGE_NAME }}"; then
                echo "Running final Laravel setup..."

                docker exec ${{ secrets.IMAGE_NAME }} php artisan key:generate

                docker exec ${{ secrets.IMAGE_NAME }} php artisan config:clear
                docker exec ${{ secrets.IMAGE_NAME }} php artisan cache:clear

                echo "✅ Deployment dan Setup Laravel Selesai."
            else
                echo "❌ GAGAL: Container tidak stabil. Cek logs dengan: docker logs ${{ secrets.IMAGE_NAME }}"
            fi

            # 4. Bersihkan image lama
            docker image prune -f